# Generated by Django 5.1.1 on 2025-01-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_category_status_tag_project_demo_project_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
