# Generated by Django 5.1.1 on 2025-01-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_project_demo_alter_project_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, default='pending', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='API.status'),
        ),
    ]
