# Generated by Django 5.1.1 on 2025-01-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_awardandhonor_education_experience_resume_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, default=20, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='API.status'),
        ),
    ]
